export const START_FETCHING_FILMS = 'START_FETCHING_FILMS';

export const ADD_FILM = 'ADD_FILM';

export const DELETE_FILM = 'DELETE_FILM';

export const CHANGE_DELETE_STATUS = 'CHANGE_DELETE_STATUS';

export const DELETE_FILM_FROM_STORE = 'DELETE_FILM_FROM_STORE';

export const ADD_FILE_FILMS = 'ADD_FILE_FILMS';

export const FILMS_TO_STORE = 'FILMS_TO_STORE';

